tap "homebrew/bundle"
tap "homebrew/command-not-found"
tap "joshmedeski/sesh"
tap "jstkdng/programs"
tap "olets/tap"
tap "saulpw/vd"
tap "sst/tap"
brew "antidote"
brew "asdf"
brew "atuin"
brew "bat"
brew "bear"
brew "boost"
brew "carapace"
brew "chafa"
brew "clang-format"
brew "cmake"
brew "coreutils"
brew "curl"
brew "deno"
brew "difftastic"
brew "direnv"
brew "duckdb"
brew "eza"
brew "fd"
brew "ffmpeg"
brew "fish"
brew "flock"
brew "folderify"
brew "fzf"
brew "fzy"
brew "gcc"
brew "gh"
brew "git-delta"
brew "git-lfs"
brew "glow"
brew "gnu-tar"
brew "graphviz"
brew "gzip"
brew "htmlq"
brew "httpie"
brew "hunspell"
brew "joshmedeski/sesh/sesh"
brew "jpeg"
brew "jq"
brew "jstkdng/programs/ueberzugpp"
brew "jupyterlab"
brew "just"
brew "lazygit"
brew "libomp"
brew "llvm"
brew "luajit"
brew "luarocks"
brew "make"
brew "mas"
brew "mise"
brew "neovim"
brew "ninja"
brew "octave"
brew "olets/tap/zsh-abbr"
brew "opam"
brew "open-mpi"
brew "pam-reattach"
brew "pandoc"
brew "pkgconf"
brew "pngpaste"
brew "poetry"
brew "pup"
brew "readline"
brew "ripgrep"
brew "saulpw/vd/visidata"
brew "sst/tap/opencode"
brew "starship"
brew "stylua"
brew "tectonic"
brew "tldr"
brew "tmux", args: ["HEAD"]
brew "trash", link: true
brew "tree"
brew "tree-sitter"
brew "unzip"
brew "uv"
brew "viu"
brew "vivid"
brew "watchexec"
brew "wget"
brew "yq"
brew "zlib"
brew "zoxide"
brew "zsh"
brew "zsh-completions"
cask "appcleaner"
cask "font-iosevka"
cask "font-iosevka-term-nerd-font"
cask "font-noto-sans-cjk"
cask "font-noto-sans-jp"
cask "font-noto-sans-mono"
cask "font-noto-sans-mono-cjk-jp"
cask "gcloud-cli"
cask "ghostty"
cask "jordanbaird-ice"
cask "karabiner-elements"
cask "keka"
cask "kitty"
cask "lunar"
cask "lyx"
cask "mactex-no-gui"
cask "middleclick"
cask "pictogram"
cask "quarto"
cask "raycast"
cask "rectangle"
cask "skim"
cask "stats"
cask "zulu"
cask "1password"
cask "1password-cli"
mas "Amphetamine", id: 937984704
mas "Keynote", id: 409183694
mas "Noir", id: 1592917505
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Telegram", id: 747648890
mas "Velja", id: 1607635845
mas "WhatsApp", id: 310633997
mas "Wipr", id: 1320666476
mas "iPreview", id: 1519213509
mas "1Password for Safari", id: 1569813296
