records = true
enter_accept = true
inline_height = 10
show_help = false
show_preview = false
show_tabs = false
style = "compact"
prefers_reduced_motion = true
workspaces = true
filter_mode_shell_up_key_binding = "directory"
search_mode_shell_up_key_binding = "prefix"
