[line_break]
disabled = true

[character]
format = "$symbol"
success_symbol = '[](bg:#2c2e34 fg:green)[\$ ](bg:green fg:#2c2e34)[▓▒](bg:#2c2e34 fg:green) '
vicmd_symbol = '[](bg:#2c2e34 fg:yellow)[V ](bg:yellow fg:#2c2e34)[▓▒](bg:#2c2e34 fg:yellow) '
error_symbol = '[](bg:#2c2e34 fg:red)[✗ ](bg:red fg:#2c2e34)[▓▒](bg:#2c2e34 fg:red) '

[directory]
style = "bg:cyan fg:#2c2e34"
read_only = " "
read_only_style = "bg:cyan fg:#2c2e34"
format = "[](bg:#2c2e34 fg:cyan)[$path]($style)[$read_only]($read_only_style)[](bg:#2c2e34 fg:cyan) "

[cmd_duration]
style = "bg:yellow fg:#2c2e34"
format = "[](bg:#2c2e34 fg:yellow)[$duration]($style)[](bg:#2c2e34 fg:yellow) "

[git_branch]
style = "bg:purple fg:#2c2e34"
format = "[](bg:#2c2e34 fg:purple)[$symbol$branch]($style)[](bg:#2c2e34 fg:purple) "

[git_status]
disabled = true
style = "bg:red fg:#2c2e34"
format = '[](bg:#2c2e34 fg:red)[$all_status$ahead_behind]($style)[](bg:#2c2e34 fg:red) '

[lua]
style = "bg:blue fg:#2c2e34"
symbol = "lua "
format = "[](bg:#2c2e34 fg:blue)[$symbol$version]($style)[](bg:#2c2e34 fg:blue) "

[cmake]
style = "bg:blue fg:#2c2e34"
symbol = "cmake "
format = "[](bg:#2c2e34 fg:blue)[$symbol$version]($style)[](bg:#2c2e34 fg:blue) "

[nodejs]
style = "bg:green fg:#2c2e34"
format = "[](bg:#2c2e34 fg:green)[$symbol$version]($style)[](bg:#2c2e34 fg:green) "

[rust]
disabled = true
style = "bg:red fg:#2c2e34"
symbol = "rust "
format = "[](bg:#2c2e34 fg:red)[$symbol$version]($style)[](bg:#2c2e34 fg:red) "

[package]
style = "bg:#ff8a65 fg:#2c2e34"
symbol = " "
format = "[](bg:#2c2e34 fg:#ff8a65)[$symbol$version]($style)[](bg:#2c2e34 fg:#ff8a65) "

[username]
show_always = true
style_root = "italic bg:white fg:#2c2e34"
style_user = "italic bg:white fg:#2c2e34"
format = "[](bg:#2c2e34 fg:white)[$user$version]($style)[](bg:#2c2e34 fg:white) "

