[tools]
python = "3.13.1"
go = "1.23"
ruby = "latest"
lua = "5.1.5"
node = "24"
codex = "latest"
pi = "latest"
biome = "latest"
pnpm = "latest"
"npm:prettier" = "latest"
"pipx:jupytext" = "latest"
"pipx:nbdime" = "latest"

[settings]
env_file = ".env"
idiomatic_version_file_enable_tools = []
auto_update = true
